(()=>{"use strict";
const spots=[
 {name:"Parc André-Citroën",badge:"N°1 OFFICIEL",best:true,reason:"Le choix prioritaire de la Ville de Paris : grandes pelouses et horizon largement dégagé. L'Association Française d'Astronomie y organise l'observation de l'éclipse avec du matériel adapté dès 19 h.",meta:"Paris 15e • 2 rue Cauchy • gratuit • observation AFA dès 19 h",query:"Parc André Citroën, 2 rue Cauchy, 75015 Paris"},
 {name:"Sommet de l'Arc de Triomphe",badge:"PANORAMA 360°",reason:"Sélectionné par l'AFA et la Ville de Paris. La hauteur et la vue à 360° réduisent fortement le risque d'avoir des immeubles proches devant l'horizon.",meta:"Paris 8e • place Charles-de-Gaulle • accès payant",query:"Arc de Triomphe, Place Charles de Gaulle, Paris"},
 {name:"Toit de la Philharmonie",badge:"POINT HAUT",reason:"Sélection AFA/Ville de Paris. Belvédère élevé au-dessus de la Villette ; l'ouverture du toit est exceptionnellement prolongée ce 12 août pour l'éclipse.",meta:"Paris 19e • 221 avenue Jean-Jaurès • belvédère gratuit",query:"Philharmonie de Paris, 221 avenue Jean Jaurès, 75019 Paris"},
 {name:"Tour Eiffel",badge:"POINT HAUT",reason:"Fait partie de la sélection AFA pour observer l'intégralité de la phase visible à Paris. Très bon dégagement en hauteur, mais accès soumis aux billets et à l'affluence.",meta:"Paris 7e • accès payant • vérifier disponibilité avant de partir",query:"Tour Eiffel, Paris"},
 {name:"Esplanade du château de Vincennes",badge:"GRAND HORIZON",reason:"Recommandée par l'AFA et la Ville de Paris. Le vaste parvis offre un horizon beaucoup plus ouvert que les rues parisiennes et évite d'être entouré de hauts immeubles.",meta:"Vincennes (94) • Esplanade Saint-Louis / avenue des Minimes • gratuit",query:"Esplanade Saint-Louis, Avenue des Minimes, Vincennes"},
 {name:"Pelouses des Invalides",badge:"ESPACE OUVERT",reason:"Sélection AFA/Ville de Paris. Grande perspective et espace ouvert ; l'AFA conseille le côté avenue du Maréchal-Gallieni pour l'observation.",meta:"Paris 7e • esplanade des Invalides • gratuit",query:"Esplanade des Invalides, Avenue du Maréchal Gallieni, Paris"},
 {name:"Jardin du Luxembourg",badge:"ESPACE OUVERT",reason:"Sélection AFA/Ville de Paris, avec recommandation de se placer près de la fontaine centrale. À privilégier si tu es déjà dans le centre de Paris.",meta:"Paris 6e • près de la fontaine centrale • fermeture annoncée vers 21 h 30",query:"Jardin du Luxembourg, Paris"},
 {name:"Pont des Arts",badge:"PONT DÉGAGÉ",reason:"Recommandé par la Ville de Paris et présent dans la sélection des ponts de l'AFA. Le pont évite une partie des obstacles immédiats au niveau de la rue.",meta:"Paris Centre • entre quai de Conti et quai François-Mitterrand • gratuit",query:"Pont des Arts, Paris"}
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const mapUrl=q=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
function card(s,i){return `<article class="spotCard${s.best?" best":""}"><div class="spotTop"><div class="spotName">${esc(s.name)}</div><div class="spotBadge${s.best?"":" alt"}">${esc(s.badge)}</div></div><div class="spotReason">${esc(s.reason)}</div><div class="spotMeta">${esc(s.meta)}</div><button class="spotUseBtn" type="button" data-spot-index="${i}">🎯 UTILISER CE SPOT DANS LA BOUSSOLE</button><div class="spotActions"><a class="spotAction primaryMap" href="${mapUrl(s.query)}" target="_blank" rel="noopener">📍 Y ALLER</a><a class="spotAction" href="https://www.afastronomie.fr/paris-eclipse" target="_blank" rel="noopener">SOURCE AFA</a></div></article>`}
function openSpots(){
 const title=document.getElementById("sheetTitle"),body=document.getElementById("sheetBody"),modal=document.getElementById("modal");if(!title||!body||!modal)return;
 title.textContent="Meilleurs spots officiels";
 body.innerHTML=`<div class="spotsIntro"><strong>Sélection vérifiée le 12 août 2026.</strong><br>Ces lieux viennent des recommandations spécifiques à l'éclipse publiées par l'Association Française d'Astronomie et la Ville de Paris. Appuie sur <strong>« Utiliser ce spot »</strong> pour que la boussole, l'heure du maximum et la météo utilisent immédiatement les coordonnées de ce lieu.</div><div class="spotsAlert"><strong>🌅 Critère essentiel :</strong> l'AFA recommande un horizon <strong>nord-ouest dégagé</strong>. Au maximum vers 20 h 17, le Soleil est très bas, autour de 8° au-dessus de l'horizon à Paris. Un bâtiment ou une rangée d'arbres peut donc suffire à cacher l'éclipse.</div><div class="spotsSectionTitle">Sélection Paris & Île-de-France</div>${spots.map(card).join("")}<div class="spotsSources"><div class="spotsSectionTitle">Sources vérifiées</div><div class="source"><strong>Association Française d'Astronomie — Où observer l'éclipse à Paris</strong><br><a href="https://www.afastronomie.fr/paris-eclipse" target="_blank" rel="noopener">Voir la sélection AFA</a></div><div class="source"><strong>Ville de Paris — Où voir l'éclipse solaire du 12 août à Paris ?</strong><br><a href="https://www.paris.fr/pages/ou-voir-l-eclipse-solaire-du-12-aout-a-paris-35868" target="_blank" rel="noopener">Voir la sélection officielle</a></div><div class="source"><strong>AFA — Observation au parc André-Citroën</strong><br><a href="https://www.afastronomie.fr/manifestations/eclipse-soleil-andre-citroen" target="_blank" rel="noopener">Voir l'événement AFA</a></div><div class="source"><strong>Région Île-de-France — événement du parc André-Citroën</strong><br><a href="https://www.iledefrance.fr/tous-les-evenements/paris-sous-les-etoiles-parc-andre-citroen-paris-15-eclipse-de-soleil" target="_blank" rel="noopener">Voir la source Région IDF</a></div><div class="spotsNote">Si tu avais déjà autorisé ta position GPS, un bouton « Revenir à ma position GPS » apparaîtra automatiquement après avoir sélectionné un spot.</div></div>`;
 modal.classList.add("open");body.scrollTop=0;
 body.querySelectorAll("[data-spot-index]").forEach(btn=>btn.addEventListener("click",()=>{const s=spots[Number(btn.dataset.spotIndex)];if(window.EclipseCompass?.selectSpot)window.EclipseCompass.selectSpot(s)}));
}
const b=document.getElementById("spotsBtn");if(b)b.addEventListener("click",openSpots);
})();